### PR TITLE
Freeze avoidance for dummy

### PR DESCRIPTION
**Pull request by shinndev**
<deleted>

### CODE REVIEW

**Comment by fokkonaut** [comment]
Please change the function `GetTileRaw()` to `GetTileRaw(vec2 Pos)` and let it return `GetTileIndex(GetPureMapIndex(Pos))`. Then you can remove those defines and just use GetTileRaw.

**Comment by shinndev** [comment]
> Please change the function `GetTileRaw()` to `GetTileRaw(vec2 Pos)` and let it return `GetTileIndex(GetPureMapIndex(Pos))`. Then you can remove those defines and just use GetTileRaw.

agreed

**Comment by ChillerDragon** [comment]
Ah nice thanks for looking into this. I also was about to improve flappy in police by a lot. Did you test your code? I mean there should be basic freeze avoidance already in police.

**Comment by shinndev** [comment]
> Ah nice thanks for looking into this. I also was about to improve flappy in police by a lot. Did you test your code? I mean there should be basic freeze avoidance already in police.
> 
> Also since this method is very generic it belongs more in the base than in the police class.

Thanks :D I did test it and works nicely. I think other dummies other than flappy doesn't need avoiding freezes. This will add a bit protection against being blocked in police. But anyway I will still move code a bit up, to dummybase.

**Comment by ChillerDragon** [comment]
Please also fix the warning:

```
dummybase.cpp:61:6: error: unused variable ‘xv’ [-Werror=unused-variable]
  int xv = (int)GetVel().x * 32;
```

Check the red cross to see warnings.

**Comment by shinndev** [comment]
> Please also fix the warning:
> 
> ```
> dummybase.cpp:61:6: error: unused variable ‘xv’ [-Werror=unused-variable]
>   int xv = (int)GetVel().x * 32;
> ```
> 
> Check the red x to see warnings.

done

**Comment by ChillerDragon** [comment]
Your oops commit broke the bot. The less specific the code is the higher it should be. The more hardcodet the lower it should be. If AvoidFreezes() is last the bot won't even read the police because it can't jump through freeze please test the code :)

**Comment by shinndev** [comment]
damn xD
tested it but without letting bot to finish the race, i just teleported it near to me. my bad
do you think reverting my second last oops commit can fix it?

**Comment by ChillerDragon** [comment]
Could you explain and show videos of what problem you are trying to solve please?

**Comment by shinndev** [comment]
> Could you explain and show videos of what problem you are trying to solve please?

about the purpose of adding avoidance?

**Comment by ChillerDragon** [comment]
> > Could you explain and show videos of what problem you are trying to solve please?
> 
> about the purpose of adding avoidance?

Yes please. What freeze exactly do you want to avoid?

**Comment by shinndev** [comment]
> > > Could you explain and show videos of what problem you are trying to solve please?
> > 
> > 
> > about the purpose of adding avoidance?
> 
> Yes please. What freeze exactly do you want to avoid?

Tile 9 one lol. There are many freezes in the map. I made code espacially for all dummies, not only for flappy. I just put in the wrong place.

**Comment by shinndev** [comment]
avoid

**Review by shinndev — COMMENTED** [review]
here i learn to use git.

**Comment by ChillerDragon** [comment]
> avoid

Yes I totally get the concept and yes that is very generic and nice and thats why I wanted it in base and all. But you call this function in a very specific mode at a very specific position in a map. There are already mechanics in place. So I wonder which tile in the BlmapChill police the bot runs into.

So that is why I expect a video or screenshot of BlmapChill because this is the only place your code will be executed on for now.
The bot can avoid freeze there already. Sure the bot is blockable and not very dodgy when it comes to the middle space but after testing your pr I can still block flappy in all the ways I could do it before. And even worse it seems to have a harder time to jump over the freeze pit now since it starts to jiggle:


https://user-images.githubusercontent.com/20344300/104598383-cd929f00-5676-11eb-9562-690157f8c1a4.mp4

**Comment by shinndev** [comment]
oh, useless pr. how about just commenting AvoidFreezes() out? so we can make it usable except flappy
i don't see any other useless parts in this pr

**Comment by ChillerDragon** [comment]
> oh, useless pr. how about just commenting AvoidFreezes() out? so we can make it usable except flappy
> i don't see any other useless parts in this pr

I wouldn't even copy it out just leave the function defintion in the base class and do not call it in any dummy mode (yet)

I do not know how @fokkonaut thinks about dead code but sounds like a nice contribution to me :)

**Comment by ChillerDragon** [comment]
Oh also when you are done please cleanup your commits. Something like this should do the job:

```
git reset --soft 2d97113fb109f2a4de315c78bf6ccaa2e27f422a
git commit --amend
git push --force
```

**Comment by shinndev** [comment]
> Oh also when you are done please cleanup your commits. Something like this should do the job:
> 
> ```
> git reset --soft 2d97113fb109f2a4de315c78bf6ccaa2e27f422a
> git commit --amend
> git push --force
> ```

oh ty

**Comment by shinndev** [comment]
ready

**Comment by ChillerDragon** [comment]
LGTM :+1:

**Pull request merged**
